plugins {
    id 'java'
    id 'application'
}


application {
    mainClass = 'main.java.d.milushev.p2p.server.Main'
}

group = 'd.milushev.p2p.server'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation project(':network-utils')
    implementation project(':env-utils')

    implementation 'org.apache.logging.log4j:log4j-api:2.26.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.26.0'
 }

test {
    useJUnitPlatform()
}

sourceSets {
    main {
        java {
            srcDirs = ['src'] // Adjust this to your existing source directory
        }
    }
}

jar {
    manifest {
        attributes(
                'Main-Class': 'main.java.d.milushev.p2p.server.Main'
        )
    }

    dependsOn configurations.runtimeClasspath

    // Bundle all runtime dependencies inside the JAR
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
